version: "3.9"

services:
  prometheus:
    container_name: eu-prometheus
    image: eu-prometheus
    build:
      context: ./docker/prometheus
    ports:
      - 9090:9090
    volumes:
      - './docker/prometheus/config:/etc/prometheus'
      - './docker/prometheus/data:/prometheus'