version: "3.9"

services:
  prometheus:
    env_file:
      - .env
    container_name: eu-prometheus
    image: eu-prometheus
    restart: unless-stopped
    build:
      context: ./docker/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - './docker/prometheus/config:/etc/prometheus'
      - './docker/prometheus/data:/prometheus'
    depends_on:
      - cadvisor

  nginx-srv-1:
    env_file:
      - .env
    container_name: nginx-srv-1
    image: 'lb-nginx-srv-1'
    build:
      context: ./docker/nginx-srv-1
    ports:
      - "${SERVICE_1_PORT}:80"
    restart: unless-stopped
    volumes:
      - "./docker/nginx-srv-1/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx-srv-1/logs/:/var/log/nginx"
      - "./docker/web/:/var/www/html"

  cadvisor:
    env_file:
      - .env
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "${CADVISOR_PORT}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - redis

  redis:
    env_file:
      - .env
    container_name: redis
    image: redis:6.0.7
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "./docker/redis/data:/data"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

  grafana:
    env_file:
      - .env
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '${GRAFANA_PORT}:3000'
    volumes:
      - './docker/grafana/data:/var/lib/grafana'
      - "./docker/grafana:/etc/grafana"
    depends_on:
      - prometheus